### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by ccurtis7** [minimaxir/tweet-generator#7]
I was able to run `tweet_generator.py` successfully for 7 epochs to create a `new_model`, but then it crashed with the following error:

`UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-2: cha racter maps to <undefined>`

Any ideas?

**Comment by ccurtis7** [comment]
This seems to be an issue with running it on a CPU. I ran it on a GPU in a CoLab notebook, and I got a little farther than I had been able to before. 

In this case, it was able to complete the specified number of epochs, but I got an error at the very end when it was trying to save the model to a file:

```
Traceback (most recent call last):
  File "tweet_generator.py", line 62, in <module>
    word_level=cfg['model_config']['word_level'])
  File "/usr/local/lib/python3.6/dist-packages/textgenrnn/textgenrnn.py", line 293, in train_new_model
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/textgenrnn/textgenrnn.py", line 227, in train_on_texts
    outputs=self.model.output[1])
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 159, in _init_graph_network
    ' (missing previous layer metadata).')
ValueError: Input tensors to a Model must come from `keras.layers.Input`. Received: Tensor("strided_slice:0", shape=(40,), dtype=float32) (missing previous layer metadata).
```

I still haven't been able to pinpoint the issue.
